exclude: /(\.git|\.venv|venv|migrations)/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: debug-statements
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        additional_dependencies: [ 'click==8.0.4' ]

        language_version: python3.7
